name: Sync dist branch
on:
  push:
    branches: [main, master]
    paths:
      - 'packages/input-otp/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build package
        run: |
          cd packages/input-otp
          pnpm build
      
      - name: Deploy to dist branch
        run: |
          set -euo pipefail

          TEMP_DIR=$(mktemp -d)
          rsync -a --delete \
            --exclude 'node_modules' \
            --exclude '.turbo' \
            packages/input-otp/ "$TEMP_DIR"/

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin dist || true
          # Create orphan dist branch if it doesn't exist
          git checkout --orphan dist || git checkout dist
          git reset --hard
          git rm -rf . || true

          # Sync package contents without development artifacts
          rsync -a --delete "$TEMP_DIR"/ ./
          rm -rf "$TEMP_DIR"

          git add .
          git commit -m "Auto-sync from master: ${{ github.sha }}" || echo "No changes"
          git push -f origin dist