name: Sync dist branch
on:
  push:
    branches: [main, master]
    paths:
      - 'packages/input-otp/**'
      - '.github/workflows/sync-dist.yml'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build package
        run: |
          cd packages/input-otp
          pnpm build
          cd "$GITHUB_WORKSPACE"
      
      - name: Deploy to dist branch
        run: |
          set -euo pipefail

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin dist || true

          if git show-ref --verify --quiet refs/heads/dist; then
            git checkout dist
          else
            git checkout --orphan dist
          fi

          git reset --hard
          git clean -fdx

          mkdir -p sync-tmp
          rsync -a --delete \
            --exclude 'node_modules' \
            --exclude '.turbo' \
            packages/input-otp/ sync-tmp/

          rsync -a --delete sync-tmp/ ./
          rm -rf sync-tmp

          git add .
          git commit -m "Auto-sync from master: ${{ github.sha }}" || echo "No changes"
          git push -f origin dist